server:
  port: 8080

spring:
  application:
    name: finances-gateway
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_URL}/eureka

urls:
  core-client: ${CORE_CLIENT_URL}
